import type { KanbanData } from "@/components";

export const initialKanbanBoard: KanbanData = {
  backlog: {
    name: "Backlog",
    color: "#94a3b8",
    cards: [
      {
        id: 1,
        title: "Implement dark mode toggle",
        tags: ["UI", "Feature"],
        tagColors: ["#7c3aed", "#2563eb"],
        progress: 0,
        comments: 2,
        attachments: 0,
        assignee: "EB",
        aColor: "#7c3aed",
        due: "Mar 15",
      },
      {
        id: 2,
        title: "Optimize database queries",
        tags: ["Backend"],
        tagColors: ["#10b981"],
        progress: 0,
        comments: 5,
        attachments: 2,
        assignee: "JC",
        aColor: "#10b981",
        due: "Mar 18",
      },
    ],
  },
  todo: {
    name: "To Do",
    color: "#3b82f6",
    cards: [
      {
        id: 3,
        title: "Design new landing page hero",
        tags: ["Design", "Marketing"],
        tagColors: ["#ec4899", "#f59e0b"],
        progress: 10,
        comments: 8,
        attachments: 4,
        assignee: "LM",
        aColor: "#ec4899",
        due: "Mar 12",
      },
      {
        id: 4,
        title: "Write API documentation",
        tags: ["Docs"],
        tagColors: ["#2563eb"],
        progress: 5,
        comments: 1,
        attachments: 0,
        assignee: "SN",
        aColor: "#06b6d4",
        due: "Mar 20",
      },
      {
        id: 5,
        title: "Setup CI/CD pipeline",
        tags: ["DevOps"],
        tagColors: ["#ef4444"],
        progress: 0,
        comments: 3,
        attachments: 1,
        assignee: "OB",
        aColor: "#f59e0b",
        due: "Mar 22",
      },
    ],
  },
  inprogress: {
    name: "In Progress",
    color: "#f59e0b",
    cards: [
      {
        id: 6,
        title: "Implement user authentication",
        tags: ["Backend", "Security"],
        tagColors: ["#10b981", "#ef4444"],
        progress: 65,
        comments: 12,
        attachments: 3,
        assignee: "NW",
        aColor: "#2563eb",
        due: "Mar 14",
      },
      {
        id: 7,
        title: "Build dashboard analytics",
        tags: ["Frontend"],
        tagColors: ["#7c3aed"],
        progress: 45,
        comments: 6,
        attachments: 2,
        assignee: "ED",
        aColor: "#10b981",
        due: "Mar 16",
      },
    ],
  },
  review: {
    name: "Review",
    color: "#7c3aed",
    cards: [
      {
        id: 8,
        title: "Code review: payment integration",
        tags: ["Review"],
        tagColors: ["#7c3aed"],
        progress: 90,
        comments: 15,
        attachments: 1,
        assignee: "JM",
        aColor: "#ef4444",
        due: "Mar 11",
      },
      {
        id: 9,
        title: "Test mobile responsiveness",
        tags: ["QA", "Mobile"],
        tagColors: ["#06b6d4", "#10b981"],
        progress: 85,
        comments: 4,
        attachments: 6,
        assignee: "AT",
        aColor: "#7c3aed",
        due: "Mar 13",
      },
    ],
  },
  done: {
    name: "Done",
    color: "#10b981",
    cards: [
      {
        id: 10,
        title: "Project kickoff meeting",
        tags: ["Meeting"],
        tagColors: ["#10b981"],
        progress: 100,
        comments: 8,
        attachments: 2,
        assignee: "MG",
        aColor: "#06b6d4",
        due: "Mar 05",
      },
      {
        id: 11,
        title: "Initial wireframes",
        tags: ["Design"],
        tagColors: ["#ec4899"],
        progress: 100,
        comments: 10,
        attachments: 5,
        assignee: "IB",
        aColor: "#f59e0b",
        due: "Mar 08",
      },
    ],
  },
};
