export type AppUser = {
  id: number;
  name: string;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  location: string;
  company: string;
  jobTitle: string;
  role: string;
  status: string;
  date: string;
  bio: string;
  timezone: string;
  initials: string;
  avatarColor: string;
  emailNotifications: boolean;
  pushNotifications: boolean;
  marketingEmails: boolean;
};

export const ASSIGNABLE_ROLES = ["Admin", "Editor", "Viewer"] as const;
export const USER_ROLES = ["All", "Admin", "Editor", "Viewer"] as const;
export const USER_STATUSES = ["All", "Active", "Inactive", "Pending"] as const;
export const ACCOUNT_STATUSES = ["Active", "Inactive", "Pending"] as const;

export const initialUsers: AppUser[] = [
  {
    id: 1,
    name: "Laura Mitchell",
    firstName: "Laura",
    lastName: "Mitchell",
    email: "laura@example.com",
    phone: "+1 (555) 123-4567",
    location: "New York, USA",
    company: "Nexora AI Inc.",
    jobTitle: "Senior Product Manager",
    role: "Admin",
    status: "Active",
    date: "Feb 28, 2025",
    bio: "Product lead managing user experience and platform operations.",
    timezone: "America/New_York",
    initials: "LM",
    avatarColor: "#2563eb",
    emailNotifications: true,
    pushNotifications: false,
    marketingEmails: false,
  },
  {
    id: 2,
    name: "James Carter",
    firstName: "James",
    lastName: "Carter",
    email: "james@example.com",
    phone: "+1 (555) 234-5678",
    location: "San Francisco, USA",
    company: "Nexora AI Inc.",
    jobTitle: "Lead Developer",
    role: "Editor",
    status: "Active",
    date: "Feb 27, 2025",
    bio: "Full-stack engineer focused on platform reliability.",
    timezone: "America/Los_Angeles",
    initials: "JC",
    avatarColor: "#10b981",
    emailNotifications: true,
    pushNotifications: true,
    marketingEmails: false,
  },
  {
    id: 3,
    name: "Sophia Nguyen",
    firstName: "Sophia",
    lastName: "Nguyen",
    email: "sophia@example.com",
    phone: "+44 20 7946 0958",
    location: "London, UK",
    company: "Nexora AI Inc.",
    jobTitle: "UX Designer",
    role: "Viewer",
    status: "Inactive",
    date: "Feb 25, 2025",
    bio: "Design systems and user research.",
    timezone: "Europe/London",
    initials: "SN",
    avatarColor: "#7c3aed",
    emailNotifications: false,
    pushNotifications: false,
    marketingEmails: true,
  },
  {
    id: 4,
    name: "Ethan Brooks",
    firstName: "Ethan",
    lastName: "Brooks",
    email: "ethan@example.com",
    phone: "+1 (555) 345-6789",
    location: "Chicago, USA",
    company: "Nexora AI Inc.",
    jobTitle: "Content Editor",
    role: "Editor",
    status: "Active",
    date: "Feb 24, 2025",
    bio: "Manages product content and documentation.",
    timezone: "America/Chicago",
    initials: "EB",
    avatarColor: "#f59e0b",
    emailNotifications: true,
    pushNotifications: false,
    marketingEmails: false,
  },
  {
    id: 5,
    name: "Olivia Peterson",
    firstName: "Olivia",
    lastName: "Peterson",
    email: "olivia@example.com",
    phone: "+1 (555) 456-7890",
    location: "Austin, USA",
    company: "Nexora AI Inc.",
    jobTitle: "Operations Manager",
    role: "Admin",
    status: "Pending",
    date: "Feb 23, 2025",
    bio: "Oversees day-to-day platform operations.",
    timezone: "America/Chicago",
    initials: "OP",
    avatarColor: "#ec4899",
    emailNotifications: true,
    pushNotifications: true,
    marketingEmails: true,
  },
  {
    id: 6,
    name: "Noah Williams",
    firstName: "Noah",
    lastName: "Williams",
    email: "noah@example.com",
    phone: "+1 (555) 567-8901",
    location: "Seattle, USA",
    company: "Nexora AI Inc.",
    jobTitle: "Data Analyst",
    role: "Viewer",
    status: "Active",
    date: "Feb 22, 2025",
    bio: "Analytics and reporting for product teams.",
    timezone: "America/Los_Angeles",
    initials: "NW",
    avatarColor: "#06b6d4",
    emailNotifications: false,
    pushNotifications: false,
    marketingEmails: false,
  },
  {
    id: 7,
    name: "Emma Johnson",
    firstName: "Emma",
    lastName: "Johnson",
    email: "emma@example.com",
    phone: "+1 (555) 678-9012",
    location: "Boston, USA",
    company: "Nexora AI Inc.",
    jobTitle: "Marketing Lead",
    role: "Editor",
    status: "Active",
    date: "Feb 21, 2025",
    bio: "Campaigns and growth initiatives.",
    timezone: "America/New_York",
    initials: "EJ",
    avatarColor: "#ef4444",
    emailNotifications: true,
    pushNotifications: false,
    marketingEmails: true,
  },
  {
    id: 8,
    name: "Liam Davis",
    firstName: "Liam",
    lastName: "Davis",
    email: "liam@example.com",
    phone: "+1 (555) 789-0123",
    location: "Denver, USA",
    company: "Nexora AI Inc.",
    jobTitle: "Support Specialist",
    role: "Viewer",
    status: "Inactive",
    date: "Feb 20, 2025",
    bio: "Customer support and onboarding.",
    timezone: "America/Denver",
    initials: "LD",
    avatarColor: "#8b5cf6",
    emailNotifications: true,
    pushNotifications: false,
    marketingEmails: false,
  },
  {
    id: 9,
    name: "Ava Thompson",
    firstName: "Ava",
    lastName: "Thompson",
    email: "ava@example.com",
    phone: "+1 (555) 890-1234",
    location: "Miami, USA",
    company: "Nexora AI Inc.",
    jobTitle: "QA Engineer",
    role: "Editor",
    status: "Active",
    date: "Feb 19, 2025",
    bio: "Quality assurance and release testing.",
    timezone: "America/New_York",
    initials: "AT",
    avatarColor: "#14b8a6",
    emailNotifications: false,
    pushNotifications: true,
    marketingEmails: false,
  },
  {
    id: 10,
    name: "Mason Garcia",
    firstName: "Mason",
    lastName: "Garcia",
    email: "mason@example.com",
    phone: "+1 (555) 901-2345",
    location: "Phoenix, USA",
    company: "Nexora AI Inc.",
    jobTitle: "System Administrator",
    role: "Admin",
    status: "Active",
    date: "Feb 18, 2025",
    bio: "Infrastructure and access control.",
    timezone: "America/Phoenix",
    initials: "MG",
    avatarColor: "#f97316",
    emailNotifications: true,
    pushNotifications: true,
    marketingEmails: false,
  },
  {
    id: 11,
    name: "Isabella Brown",
    firstName: "Isabella",
    lastName: "Brown",
    email: "isabella@example.com",
    phone: "+1 (555) 012-3456",
    location: "Portland, USA",
    company: "Nexora AI Inc.",
    jobTitle: "Junior Analyst",
    role: "Viewer",
    status: "Pending",
    date: "Feb 17, 2025",
    bio: "New team member in onboarding.",
    timezone: "America/Los_Angeles",
    initials: "IB",
    avatarColor: "#6366f1",
    emailNotifications: true,
    pushNotifications: false,
    marketingEmails: false,
  },
  {
    id: 12,
    name: "Logan Wilson",
    firstName: "Logan",
    lastName: "Wilson",
    email: "logan@example.com",
    phone: "+1 (555) 111-2222",
    location: "Atlanta, USA",
    company: "Nexora AI Inc.",
    jobTitle: "DevOps Engineer",
    role: "Editor",
    status: "Active",
    date: "Feb 16, 2025",
    bio: "CI/CD pipelines and deployment automation.",
    timezone: "America/New_York",
    initials: "LW",
    avatarColor: "#0ea5e9",
    emailNotifications: true,
    pushNotifications: true,
    marketingEmails: false,
  },
];

export function syncUserName(user: AppUser): AppUser {
  return {
    ...user,
    name: `${user.firstName} ${user.lastName}`.trim(),
    initials: `${user.firstName[0] ?? ""}${user.lastName[0] ?? ""}`.toUpperCase(),
  };
}
