/** @deprecated Import from `@/components` instead */
export {
  ChartTip,
  Ring,
  RingChart,
  PI,
  AvatarInitials,
  StatCard,
  StatsGrid,
  Placeholder,
  PlaceholderPage,
  PageStack,
  PageGrid,
  ChartCard,
  DataTable,
  type TableColumn,
  TablePagination,
  UsersTable,
  OrdersTable,
  ProductsTable,
  EmployeesTable,
  EditableProductsTable,
  KanbanBoard,
} from "@/components";
