"use client";

import { useState } from "react";
import { Sparkles, Copy, Check, RefreshCw, Download } from "lucide-react";
import { PillBtn } from "./_atoms";
import { CONTENT_TYPES, TONES, LANGS, MODELS } from "./_types";

function wordCount(s: string) {
    return s.trim().split(/\s+/).filter(Boolean).length;
}

interface ContentViewProps {
    modelLabel: string;
}

export function ContentView({ modelLabel }: ContentViewProps) {
    const [ctTopic, setCtTopic] = useState("AI-driven analytics dashboards");
    const [ctType, setCtType] = useState(CONTENT_TYPES[0]);
    const [ctTone, setCtTone] = useState(TONES[0]);
    const [ctLang, setCtLang] = useState("English");
    const [ctLen, setCtLen] = useState("Medium");
    const [ctKw, setCtKw] = useState("");
    const [ctOut, setCtOut] = useState(
        "# AI-Driven Analytics Dashboards\n\nIn today's fast-paced landscape, AI-driven dashboards transform raw data into actionable intelligence.\n\n## Why It Matters\nLegacy tools lag behind real-time events. AI surfaces anomalies instantly.\n\n## Key Benefits\n- Real-time anomaly detection\n- Predictive forecasting\n- Natural language querying\n\nStart with a focused pilot — pick one KPI, connect your data source, and let the AI establish baselines.",
    );
    const [ctLoading, setCtLoading] = useState(false);
    const [ctCopied, setCtCopied] = useState(false);

    function generateContent() {
        setCtLoading(true);
        setTimeout(() => {
            setCtOut(
                `# ${ctTopic}\n\nThis is a simulated ${ctTone.toLowerCase()} ${ctType.toLowerCase()} generated by ${modelLabel}.\n\n## Introduction\nIn today's competitive landscape, understanding ${ctTopic} is critical for success.\n\n## Main Points\n- Key insight drawn from current trends\n- Practical application for your audience\n- Evidence-backed recommendation\n\n## Conclusion\nStart small, measure results, and iterate quickly. The organizations winning today treat this not as a novelty but as core infrastructure.\n\n${ctKw ? `**Keywords:** ${ctKw}` : ""}`,
            );
            setCtLoading(false);
        }, 1200);
    }

    return (
        <div className="flex-1 flex min-h-0 overflow-hidden">
            {/* Settings panel */}
            <div className="w-[280px] border-r border-border overflow-y-auto p-5 shrink-0">
                <div className="font-bold text-[15px] mb-4">Content Settings</div>

                {[
                    {
                        label: "Topic",
                        el: (
                            <input
                                value={ctTopic}
                                onChange={(e) => setCtTopic(e.target.value)}
                                className="w-full py-[7px] px-[10px] rounded-lg border border-border bg-muted text-foreground text-[13px] outline-none"
                            />
                        ),
                    },
                    {
                        label: "Content Type",
                        el: (
                            <select
                                value={ctType}
                                onChange={(e) => setCtType(e.target.value)}
                                className="w-full py-[7px] px-[10px] rounded-lg border border-border bg-card text-foreground text-[13px]"
                            >
                                {CONTENT_TYPES.map((t) => <option key={t}>{t}</option>)}
                            </select>
                        ),
                    },
                    {
                        label: "Language",
                        el: (
                            <select
                                value={ctLang}
                                onChange={(e) => setCtLang(e.target.value)}
                                className="w-full py-[7px] px-[10px] rounded-lg border border-border bg-card text-foreground text-[13px]"
                            >
                                {LANGS.map((l) => <option key={l}>{l}</option>)}
                            </select>
                        ),
                    },
                    {
                        label: "SEO Keywords",
                        el: (
                            <input
                                value={ctKw}
                                onChange={(e) => setCtKw(e.target.value)}
                                placeholder="comma separated"
                                className="w-full py-[7px] px-[10px] rounded-lg border border-border bg-muted text-foreground text-[13px] outline-none"
                            />
                        ),
                    },
                ].map(({ label, el }) => (
                    <div key={label} className="mb-[14px]">
                        <label className="text-xs font-semibold block mb-[5px] text-muted-foreground">
                            {label}
                        </label>
                        {el}
                    </div>
                ))}

                <div className="mb-[14px]">
                    <label className="text-xs font-semibold block mb-[5px] text-muted-foreground">
                        Tone
                    </label>
                    <div className="flex flex-wrap gap-[5px]">
                        {TONES.map((t) => (
                            <PillBtn key={t} active={ctTone === t} onClick={() => setCtTone(t)}>
                                {t}
                            </PillBtn>
                        ))}
                    </div>
                </div>

                <div className="mb-5">
                    <label className="text-xs font-semibold block mb-[5px] text-muted-foreground">
                        Length
                    </label>
                    <div className="flex gap-[5px]">
                        {["Short", "Medium", "Long"].map((l) => (
                            <PillBtn key={l} active={ctLen === l} onClick={() => setCtLen(l)}>
                                {l}
                            </PillBtn>
                        ))}
                    </div>
                </div>

                <button
                    onClick={generateContent}
                    disabled={!ctTopic.trim() || ctLoading}
                    className="w-full py-[9px] rounded-[9px] border-none bg-primary text-white cursor-pointer font-bold text-[13px] flex items-center justify-center gap-[6px] disabled:opacity-60"
                >
                    <Sparkles size={13} /> {ctLoading ? "Generating…" : "Generate"}
                </button>
            </div>

            {/* Output panel */}
            <div className="flex-1 flex flex-col min-w-0">
                <div className="px-[18px] py-3 border-b border-border flex items-center justify-between shrink-0">
                    <span className="font-bold text-sm">Output</span>
                    <div className="flex gap-[6px]">
                        <button
                            onClick={() => {
                                navigator.clipboard.writeText(ctOut).catch(() => { });
                                setCtCopied(true);
                                setTimeout(() => setCtCopied(false), 1500);
                            }}
                            className="px-[11px] py-[5px] rounded-[7px] border border-border bg-card cursor-pointer text-xs font-semibold flex items-center gap-[5px] text-foreground"
                        >
                            {ctCopied ? <Check size={12} className="text-[#10b981]" /> : <Copy size={12} />}
                            {ctCopied ? "Copied" : "Copy"}
                        </button>
                        <button
                            onClick={generateContent}
                            disabled={ctLoading}
                            className="px-[11px] py-[5px] rounded-[7px] border border-border bg-card cursor-pointer text-xs font-semibold flex items-center gap-[5px] text-foreground disabled:opacity-60"
                        >
                            <RefreshCw size={12} /> Rewrite
                        </button>
                        <button className="px-[11px] py-[5px] rounded-[7px] border border-border bg-card cursor-pointer text-xs font-semibold flex items-center gap-[5px] text-foreground">
                            <Download size={12} /> Export
                        </button>
                    </div>
                </div>

                <textarea
                    value={ctOut}
                    onChange={(e) => setCtOut(e.target.value)}
                    className="flex-1 px-6 py-5 border-none outline-none resize-none text-sm leading-[1.75] text-foreground bg-transparent font-[inherit]"
                />

                <div className="px-6 py-2 border-t border-border text-xs text-muted-foreground flex gap-[14px] shrink-0">
                    <span>
                        <strong className="text-foreground">{wordCount(ctOut)}</strong> words
                    </span>
                    <span>
                        <strong className="text-foreground">{ctOut.length}</strong> chars
                    </span>
                    <span>Model: {modelLabel}</span>
                </div>
            </div>
        </div>
    );
}
